CREATE TABLE IF NOT EXISTS AVG_NET_PRICE_TABLE (
	ID			int			NOT NULL UNIQUE PRIMARY KEY,
	price		int			NOT NULL
);

CREATE TABLE IF NOT EXISTS SCHOOL_AVG_NET_PRICE (
    school_id	int			NOT NULL UNIQUE,
	price_id	int			NOT NULL,
    PRIMARY KEY (school_id, price_id),
    FOREIGN KEY (school_id) REFERENCES SCHOOL_TABLE (ID),
    FOREIGN KEY (price_id) REFERENCES AVG_NET_PRICE_TABLE (ID)
);

CREATE VIEW AVG_NET_PRICE_PUBLIC_TABLE AS SELECT * FROM AVG_NET_PRICE WHERE ID IN (SELECT price_id FROM SCHOOL_AVG_NET_PRICE WHERE school_id IN (SELECT school_id FROM SCHOOL_OWN WHERE control_id = (SELECT ID FROM OWN_TABLE WHERE control = 0) ) ); 

CREATE VIEW AVG_NET_PRICE_PRIVATE_TABLE AS SELECT * FROM AVG_NET_PRICE WHERE ID IN (SELECT price_id FROM SCHOOL_AVG_NET_PRICE WHERE school_id IN (SELECT school_id FROM SCHOOL_OWN WHERE control_id = (SELECT ID FROM OWN_TABLE WHERE control = 1 OR control = 2) ) ); 

CREATE TABLE IF NOT EXISTS YEAR_TABLE (
	ID			int				NOT NULL UNIQUE PRIMARY KEY,
    year_type	varchar(64)		NOT NULL UNIQUE
);

# INSERT INTO YEAR_TABLE VALUES (1,'program'),(2,'other');

CREATE TABLE IF NOT EXISTS SCHOOL_YEAR (
	school_id		int			NOT NULL UNIQUE,
    year_id			int			NOT NULL,
    PRIMARY KEY (school_id, year_id),
    FOREIGN KEY (school_id) REFERENCES SCHOOL_TABLE (ID),
    FOREIGN KEY (year_id) REFERENCES YEAR_TABLE (ID)    
);

CREATE VIEW AVG_NET_PRICE_PROG_YEAR_TABLE AS SELECT * FROM AVG_NET_PRICE WHERE ID IN (SELECT price_id FROM SCHOOL_AVG_NET_PRICE WHERE school_id IN (SELECT school_id FROM SCHOOL_YEAR WHERE year_id = (SELECT ID FROM YEAR_TABLE WHERE year_type = 'program') ) ); 

CREATE VIEW AVG_NET_PRICE_OTHER_ACAD_YEAR_TABLE AS SELECT * FROM AVG_NET_PRICE WHERE ID IN (SELECT price_id FROM SCHOOL_AVG_NET_PRICE WHERE school_id IN (SELECT school_id FROM SCHOOL_YEAR WHERE year_id = (SELECT ID FROM YEAR_TABLE WHERE year_type = 'other') ) ); 

CREATE TABLE IF NOT EXISTS NET_PRICE_TABLE (
	ID		int		NOT NULL UNIQUE PRIMARY KEY,
    price	int		NOT NULL
);

